# Generated by Django 3.2.25 on 2025-01-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donorregister',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=100)),
                ('bloodtype', models.CharField(max_length=100)),
                ('mobno', models.IntegerField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('locn', models.CharField(max_length=300)),
                ('hname', models.CharField(max_length=300)),
                ('organavail', models.CharField(max_length=300)),
                ('chronicdisease', models.CharField(max_length=300)),
                ('infectious', models.CharField(max_length=200)),
                ('cancerhistory', models.CharField(max_length=200)),
                ('medications', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='receiverregister',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rname', models.CharField(max_length=100)),
                ('rage', models.IntegerField(max_length=100)),
                ('rbloodtype', models.CharField(max_length=100)),
                ('rmobno', models.IntegerField(max_length=100)),
                ('rpwd', models.CharField(max_length=100)),
                ('rlocn', models.CharField(max_length=300)),
                ('rhname', models.CharField(max_length=300)),
                ('organneed', models.CharField(max_length=300)),
            ],
        ),
    ]
